services:
  nginx:
    image: nginx:1.22.1-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx/sites.conf:/etc/nginx/confd/sites.conf
      - ./proxy/nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - web
      - api

  web:
    container_name: client
    build:
      context: ./blog-client
      dockerfile: Dockerfile.prd
    expose:
      - '3000'
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_WEB}
    depends_on:
      - api

  api:
    container_name: server
    build:
      context: ./blog-server
      dockerfile: Dockerfile.prd
    expose:
      - '3030'
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_API}
