version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api

  web:
    container_name: client
    build:
      context: ./blog-client
    ports:
      - 3000:3000
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_WEB}

  api:
    container_name: server
    build:
      context: ./blog-server
    expose:
      - '3030'
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN_API}
