services:
  nginx:
    container_name: nginx
    image: nginx:1.22.1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
