FROM node:18-alpine

RUN mkdir -p /server
WORKDIR /server
COPY . /server/

RUN wget -q -t3 'https://packages.doppler.com/public/cli/rsa.8004D9FF50437357.key' -O /etc/apk/keys/cli@doppler-8004D9FF50437357.rsa.pub && \
  echo 'https://packages.doppler.com/public/cli/alpine/any-version/main' | tee -a /etc/apk/repositories && \
  apk add doppler

ARG DOPPLER_TOKEN

RUN yarn

ENV HOST 0.0.0.0
EXPOSE 3030

CMD ["doppler", "run", "--", "yarn", "start:dev"]
