name: API Server CI/CD With Docker

on:
  push:
    branches:
      - main
    paths:
      - 'blog-server/**'

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/server
  VERSION: ${{ github.sha }}
  NAMNE: server
  DOCKERFILE_PATH: ./blog_server/Dockerfile

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ env. DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
