name: API Server Deploy with Docker

on:
  workflow_run:
    workflows: ['API Server Build with Docker']
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'blog-server/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and execute a deployment script
        uses: appleboy/ssh-action@master
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          SERVICE_NAME: ${{ secrets.API_SERVICE_NAME }}
          IMAGE_NAME: ${{ secrets.API_IMAGE_NAME }}
          DOPPLER_TOKEN: ${{ secrets.API_DOPPLER_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: TARGET_DIR,SERVICE_NAME,IMAGE_NAME,DOPPLER_TOKEN
          script: |
            cd "$TARGET_DIR"
            ./deploy.sh "$TARGET_DIR" "$SERVICE_NAME" "$IMAGE_NAME" "$DOPPLER_TOKEN"
