name: Check Markdown Header Validity
on:
  push:
    branches:
      - main

jobs:
  check_header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Check Markdown Header
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.md$')
          for file in ${changed_files}; do
              echo "Check ${file} Header"
              npm run check "${file}"
            done
