name: Check Markdown Header Validity
on:
  push:
    branches:
      - main

jobs:
  check_header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Get pushed files
        id: get_files
        run: |
          pushed_files=$(git diff-tree --no-commit-id --name-status -r ${{ github.sha }})

          echo ${pushed_files}

          # set multiline output parameter
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "PUSHED_FILES<<$EOF" >> "$GITHUB_OUTPUT"
          echo "${pushed_files}" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: Send request to server
        run: |
          pushed_files="${{ steps.get_files.outputs.PUSHED_FILES}}"

          IFS=$'\n'
          for line in ${pushed_files}; do
            if [[ "$line" == *.md ]]; then
              echo "Send request of ${line}"
              npm run send "${line}"
            fi
          done
