name: Web Server Build With Docker

on:
  push:
    branches:
      - main
    paths:
      - 'blog-client/**'

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/client
  VERSION: ${{ github.sha }}
  NAMNE: client

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./blog-client
          file: ./blog-client/Dockerfile.build
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and execute a deployment script
        uses: appleboy/ssh-action@master
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          SERVICE_NAME: ${{ secrets.WEB_SERVICE_NAME }}
          IMAGE_NAME: ${{ secrets.WEB_IMAGE_NAME }}
          DOPPLER_TOKEN: ${{ secrets.WEB_DOPPLER_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: TARGET_DIR,SERVICE_NAME,IMAGE_NAME,DOPPLER_TOKEN
          script: |
            cd "$TARGET_DIR"
            git pull origin main
            ./deploy.sh "$TARGET_DIR" "$SERVICE_NAME" "$IMAGE_NAME" "$DOPPLER_TOKEN"
